# Generated by Django 4.2.5 on 2023-10-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('cse(regular)', 'cse(r)'), ('cse(honors)', 'cse(h)'), ('cs&it', 'csit')], max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('odd', 'odd'), ('even', 'even')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='course',
            table='course_table',
        ),
        migrations.AlterModelTable(
            name='faculty',
            table='faculty_table',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student_table',
        ),
    ]
